baseURL = 'https://news.perthchat.org/'
languageCode = 'en-us'
title = 'Perthchat news is gone! Our cloud provider gobbled it up... If you are not redirected automatically, follow this <a href="https://michael5collins.com">link to michael5collins.com</a>'
